global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["localhost:8086"]
        labels:
          service: "ml-gateway"